function [fout,gof,str] = customGaussPeak(X,Y,opts)

if nargin==2
   opts = struct;
   opts.Guess_Xc = [0];
   opts.Guess_Sigma = [5];
end

y = @(A,x0,s,x) A*exp(-(x-x0).^2/(2*s.^2));

nPeaks = length(xC);
    
switch nPeaks
    case 1
        myfit = fittype(...
            @(bg,...
            A1,x1,s1,x) ...
            bg + ...
            y(A1,x1,s1,x),...
            'independent',{'x'},...
            'coefficients',{'bg','A1','x1','s1'});        
    case 2
        myfit = fittype(...
            @(bg,...
            A1,x1,s1,...
            A2,x2,s2,x) ...
            bg + ...
            y(A1,x1,s1,x) + ...
            y(A2,x2,s2,x),...
            'independent',{'x'},...
            'coefficients',{'bg','A1','x1','s1','A2','x2','s2'});  
    case 3
        myfit = fittype(...
            @(bg,...
            A1,x1,s1,...
            A2,x2,s2,...
            A3,x3,s3,x) ...
            bg + ...
            y(A1,x1,s1,x) + ...
            y(A2,x2,s2,x) + ...
            y(A3,x3,s3,x),...
            'independent',{'x'},...
            'coefficients',...
            {'bg','A1','x1','s1','A2','x2','s2','A3','x3','s3'});        
    case 4
        myfit = fittype(...
            @(bg,...
            A1,x1,s1,...
            A2,x2,s2,...
            A3,x3,s3,...
            A4,x4,s4,x) ...
            bg + ...
            y(A1,x1,s1,x) + ...
            y(A2,x2,s2,x) + ...
            y(A3,x3,s3,x) + ...
            y(A3,x3,s3,x),...
            'independent',{'x'},...
            'coefficients',...
            {'bg','A1','x1','s1','A2','x2','s2','A3','x3','s3','A4','x4','s4'});  
        
end
fitopt = fitoptions(myfit);

%% Find Guesses
StartPoint = zeros(1,length(coeffnames(myfit)));

R = range(Y);

% Find points nearest to each provided center


%%
fitopt.StartPoint = opts.StartPoint;    

[fout,gof,output] = fit(X,Y,myfit,opt)

switch opts.NumPeaks
        case 1
            str = ['$(A_1,f_1,s_1)$' newline '$(' ...
                num2str(round(fout.A1,2)) ...
                ',' num2str(round(fout.x1,2)) '~\mathrmrm{' opts.XUnit '},' ...
                num2str(round(fout.s1,2)) '~\mathrmrm{' opts.XUnit '})'];           
end
 


    
end
